version: '2'
services:
  master:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --port 6379 --requirepass password  --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
