version: '2'
networks:
    mysql:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.18.0.0/24
services:
    master1:
        container_name: master1
        restart: always
        volumes:
            - "./mysql-master1/data:/var/lib/mysql"
            - "./mysql-master1/conf/my.cnf:/etc/my.cnf"
            - "./mysql-master1/logs:/var/log/mysql"
            - "./mysql-master1/init:/docker-entrypoint-initdb.d/"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0.17"
        ports:
            - "3307:3306"
        networks:
            mysql:
                ipv4_address: 192.18.0.2
    master2:
        container_name: master2
        restart: always
        volumes:
            - "./mysql-master2/data:/var/lib/mysql"
            - "./mysql-master2/conf/my.cnf:/etc/my.cnf"
            - "./mysql-master2/logs:/var/log/mysql"
            - "./mysql-master2/init:/docker-entrypoint-initdb.d/"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0.17"
        ports:
            - "3310:3306"
        networks:
            mysql:
                ipv4_address: 192.18.0.5
    slave12:
        container_name: slave12
        restart: always
        volumes:
            - "./mysql-slave12/data:/var/lib/mysql"
            - "./mysql-slave12/conf/my.cnf:/etc/my.cnf"
            - "./mysql-slave12/logs:/var/log/mysql"
            - "./mysql-slave12/init:/docker-entrypoint-initdb.d/"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0.17"
        ports:
            - "3308:3306"
        depends_on:
            - master1
        networks:
            mysql:
                ipv4_address: 192.18.0.3
        links:
          - master1
    slave11:
        container_name: slave11
        restart: always
        volumes:
            - "./mysql-slave11/data:/var/lib/mysql"
            - "./mysql-slave11/conf/my.cnf:/etc/my.cnf"
            - "./mysql-slave11/logs:/var/log/mysql"
            - "./mysql-slave11/init:/docker-entrypoint-initdb.d/"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0.17"
        ports:
            - "3309:3306"
        depends_on:
            - master1
        networks:
            mysql:
                ipv4_address: 192.18.0.4
        links:
            - master1
    slave21:
        container_name: slave21
        restart: always
        volumes:
            - "./mysql-slave21/data:/var/lib/mysql"
            - "./mysql-slave21/conf/my.cnf:/etc/my.cnf"
            - "./mysql-slave21/logs:/var/log/mysql"
            - "./mysql-slave21/init:/docker-entrypoint-initdb.d/"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0.17"
        ports:
            - "3311:3306"
        depends_on:
            - master2
        networks:
            mysql:
                ipv4_address: 192.18.0.6
        links:
            - master2
    slave22:
        container_name: slave22
        restart: always
        volumes:
            - "./mysql-slave22/data:/var/lib/mysql"
            - "./mysql-slave22/conf/my.cnf:/etc/my.cnf"
            - "./mysql-slave22/logs:/var/log/mysql"
            - "./mysql-slave22/init:/docker-entrypoint-initdb.d/"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0.17"
        ports:
            - "3312:3306"
        depends_on:
            - master2
        networks:
            mysql:
                ipv4_address: 192.18.0.7
        links:
            - master2

