apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.100.11.36:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: DS_PROMETHEUS
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.100.11.36:9090
    basicAuth: false
    isDefault: false
    editable: true