version: '2'
services:
    mysql-standalone:
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        image: "mysql:8.0.17"
        restart: always
        volumes:
            - "./data:/var/lib/mysql"
            - "./conf/my.cnf:/etc/my.cnf"
            - "./init:/docker-entrypoint-initdb.d/"
        ports:
            - "3336:3306"
        container_name: mysql-standalone
