version: '2.0'

services:
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    volumes:
      - ./prometheus-fd.yml:/etc/prometheus/prometheus-fd.yml:ro
      - ./data:/data
      - ./rules:/etc/prometheus/rules/
      - ./file-sd/:/usr/local/prometheus/groups/
    ports:
      - 9090:9090
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    command:
      - --config.file=/etc/prometheus/prometheus-fd.yml
      - --storage.tsdb.path=/data
    depends_on:
      - cadvisor
      - alertmanager
      - node-exporter
      - mysqld-exporter
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  node-exporter:
    image: 'prom/node-exporter:latest'
    container_name: node-exporter
    ports:
      - 9100:9100
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    depends_on:
      - prometheus
  alertmanager:
    image: 'prom/alertmanager:latest'
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./alertmanager/tmpl/:/etc/alertmanager-tmpl/
    ports:
      - 9093:9093
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - TZ=Asia/Shanghai
      - DATA_SOURCE_NAME=root:123456@(10.100.11.36:3336)/
