global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
rule_files:
  - /etc/prometheus/rules/*.rules
scrape_configs:
  - job_name: open-platform-service
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 10.100.11.36:8102
  - job_name: operation-service
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 10.100.11.36:8101
  - job_name: openplatform-web
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 10.100.11.36:8201
  - job_name: operation-web
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 10.100.11.36:8202
  - job_name: speech-gateway
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 10.100.11.36:8081
  - job_name: cadvisor
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: 'node-exporter'
    file_sd_configs:
      - files: ['/usr/local/prometheus/groups/nodegroups/*.json']