global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
rule_files:
  - /etc/prometheus/rules/*.rules
scrape_configs:
  - job_name: 'file_ds'
    file_sd_configs:
      - files: ['/usr/local/prometheus/groups/fd/*.json']
  - job_name: 'springcloud-micro-service'
    metrics_path: /actuator/prometheus
    file_sd_configs:
      - files: ['/usr/local/prometheus/groups/micro-service/*.json']
