global:
  resolve_timeout: 5m
  smtp_from: 'cwy996jisuanji@163.com'
  smtp_smarthost: 'smtp.163.com:465'
  smtp_auth_username: 'cwy996jisuanji@163.com'
  smtp_auth_password: 'LIWPUWYWHWWYYJJK'
  smtp_require_tls: false
  smtp_hello: '163.com'
templates:
  - '/etc/alertmanager-tmpl/email.tmpl'
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: 'cwy996jisuanji@126.com'
        html: '{{ template "email.to.html" . }}'
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']