version: '2'
services:
  elasticsearch-stand-alone:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    container_name: elasticsearch-stand-alone
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 19200:9200
      - 19300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data


  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name: elasticsearch-head
    restart: always
    ports:
      - 9100:9100
